name: Security checks

on:
  push:
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python m pip install -r requirements.txt

      - name: Install Bandit
        run: python -m pip install bandit

      - name: Run Bandit
        run: bandit -r . -x ./ .venv

      -name: Install pip-audit
       run: python -m pip install pip-audit

      -name: Run pip-audit
       run: pip-audit 
