name: Verification de securite

on:
  push:
  pull_request:

jobs:
  bandit:
    runs-on: ubuntu-latest

    steps:
      - name: Recuperer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Installer Bandit
        run: pip install bandit

      - name: Analiser le code 
        run: bandit -r . -ll
