	name: Security checks
	
     	on:
     	  push:
     	  pull_request:
     	
     	jobs:
     	  security:
     	    runs-on: ubuntu-latest
    	
    	    steps:
    	      - name: Recuperer le depot 
    	        uses: actions/checkout@v4
    	
    	      - name: Installer Python
    	        uses: actions/setup-python@v5
    	        with:
    	          python-version: "3.12"
    	
    	      - name: Installer les dependances

